### ISSUE TITLE
Create proper readme file

### ISSUE THREAD

**Issue by FRosner** [FRosner/BeeHive#5]
We need to improve the README.md file.
- mention how to build the project
- explain basic functionality
- how to configure (command line arguments and properties files)
- explain thread / stack size limitations
- include screenshots?

**Comment by FRosner** [comment]
@sbarsbar1 what is the progress on this one?

**Comment by FRosner** [comment]
@3ll060 can you follow up on this?

**Comment by ghost** [comment]
@sbarsbar1 @FRosner No! To busy in eating bananas!
